spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: app-feature-toggle-java
  data:
    mongodb:
      auto-index-creation: true
      uri: "mongodb://leonardo:123456@localhost:27017/featureToggle?authSource=admin"
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/featureToggle
    username: leonardo
    password: 123456
  database:
    driverClassName: org.postgresql.Driver
unleash:
  app-name: app-feature-toggle-unleash-java
  instance-id: app-feature-toggle-java
  unleash-api: http://localhost:4242/api
  api-key: "default:development.a6ca0c8371fb20169cbadc11ea501996ec3200251f0e18fe083dbdde
  synchronous-fetch-on-initialisation: true
